{{- if .Values.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
  labels:
    app: {{ template "opentelemetryhelm.name" . }}
    chart: {{ template "opentelemetryhelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}