{{- if .Values.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: multicluster-observability-metrics
  namespace: open-cluster-management-addon-observability
  labels:
    {{- include "metricshelm.labels" . | indent 4 }}
{{- end }}
