receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:

exporters:
  otlphttp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
